analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.2244580648839474
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.8134957426227629
  brandStrength: 0.7273479378782213
  rhythmicContrast: 0.9861214028205723
  brandColors: []
  lightness: 0.2828394419047982
purpose: []
favicon: null
name: paulk-blog
typography_spectrum: 0.7228826598729938
